#Server configuration
server:
  port: ${PORT:8085}

#Database configuration
spring:
  datasource:
    url: ${URL}
    username: ${USER_NAME}
    password: ${PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect

  #WebClient configuration
  webflux:
    client:
      max-in-memory-size: 16MB
    codec:
      max-in-memory-size: 16MB

#Springdoc configuration
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html

#Logger configuration
logging:
  level:
    root: info
    org:
      springframework: debug
    # Add WebClient specific logging
    org.springframework.web.reactive.function.client.WebClient: DEBUG
  file:
    name: logs/application.log
    max-size: 10MB
    max-history: 7

#External APIs configuration
external-apis:
  api1:
    base-url: http://localhost:8086/api/v1/user
    connection-timeout: 5000
    read-timeout: 5000
    write-timeout: 5000
    retry:
      max-attempts: 3
      initial-interval: 1000
      multiplier: 2.0
      max-interval: 10000