#Server configuration
server:
  port: 8081

  #WebClient configuration
  webflux:
    client:
      max-in-memory-size: 16MB
    codec:
      max-in-memory-size: 16MB

#Springdoc configuration
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html

#Logger configuration
logging:
  level:
    root: info
    org:
      springframework: debug
    org.springframework.web.reactive.function.client.WebClient: DEBUG
  file:
    name: logs/application.log
    max-size: 10MB
    max-history: 7

#External APIs configuration
external-apis:
  api1:
    base-url: https://parfinancieraspringboot-2.onrender.com/swagger-ui.html/api/v1/user
    connection-timeout: 5000
    read-timeout: 5000
    write-timeout: 5000
    retry:
      max-attempts: 3
      initial-interval: 1000
      multiplier: 2.0
      max-interval: 10000

#perfil test
